# Customer Churn & Retention Platform

## 02 — Feature Engineering & Baseline Modelling

This notebook prepares the cleaned customer data for machine learning and develops an initial baseline churn prediction model.

### Objectives

- Define the modelling target and predictor variables
- Remove non-predictive identifiers
- Prepare numerical and categorical features
- Split the data into training and test sets
- Build a reproducible preprocessing pipeline
- Train a baseline classification model
- Evaluate performance using appropriate churn metrics

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/processed/telco_churn_clean.csv")

df.shape

(7043, 21)

## 1. Define Features and Target

The target variable is `Churn`, which indicates whether a customer left the company.

`customerID` is excluded from the predictor variables because it is a unique identifier rather than a meaningful customer characteristic. Including it could introduce noise and encourage the model to learn patterns associated with arbitrary identifiers rather than generalisable churn behaviour.

In [3]:
X = df.drop(columns=["customerID", "Churn"])
y = df["Churn"].map({
    "No": 0,
    "Yes": 1
})

print("X shape:", X.shape)
print("y shape:", y.shape)

y.value_counts()

X shape: (7043, 19)
y shape: (7043,)

Churn
0    5174
1    1869
Name: count, dtype: int64

## 2. Train/Test Split

The dataset is divided into training and test sets before preprocessing or model fitting.

The training set is used to learn preprocessing transformations and train the model, while the test set is held back for final evaluation on unseen customers.

A stratified split is used so that both sets preserve approximately the same churn proportion as the full dataset.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Test features:", X_test.shape)

print("\nTraining churn rate:")
print(y_train.value_counts(normalize=True).round(4))

print("\nTest churn rate:")
print(y_test.value_counts(normalize=True).round(4))

Training features: (5634, 19)
Test features: (1409, 19)

Training churn rate:
Churn
0    0.7346
1    0.2654
Name: proportion, dtype: float64

Test churn rate:
Churn
0    0.7346
1    0.2654
Name: proportion, dtype: float64

## 3. Feature Preprocessing

The predictor variables contain both numerical and categorical features.

Numerical features will be standardised, while categorical features will be converted into numerical representations using one-hot encoding. These transformations will be combined into a preprocessing pipeline so that the same transformations can later be applied consistently to unseen data.

In [5]:
numerical_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical features:")
print(numerical_features)

print("\nCategorical features:")
print(categorical_features)

print("\nNumber of numerical features:", len(numerical_features))
print("Number of categorical features:", len(categorical_features))

Numerical features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Number of numerical features: 4
Number of categorical features: 15

/var/folders/s1/2yfy3xy16y7dfk1r0q_ssnkm0000gn/T/ipykernel_12082/319291553.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_train.select_dtypes(

In [6]:
numerical_features = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

categorical_features = [
    column for column in X_train.columns
    if column not in numerical_features
]

print("Numerical features:")
print(numerical_features)

print("\nCategorical features:")
print(categorical_features)

print("\nNumber of numerical features:", len(numerical_features))
print("Number of categorical features:", len(categorical_features))

Numerical features:
['tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features:
['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Number of numerical features: 3
Number of categorical features: 16

In [8]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['tenure', 'MonthlyCharges', 'TotalCharges']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'SeniorCitizen', 'Partner',
                                  'Dependents', 'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [11]:
baseline_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(
                max_iter=1000,
                random_state=42
            )
        )
    ]
)

baseline_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

### Model Training

The baseline pipeline is fitted using the training data. During this process, the preprocessing transformations are learned from the training set and the logistic regression classifier is then trained on the transformed features.

In [12]:
baseline_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [13]:
y_pred = baseline_model.predict(X_test)

y_pred[:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [14]:
pd.Series(y_pred).value_counts()

0    1091
1     318
Name: count, dtype: int64

## 5. Baseline Model Evaluation

Because the churn target is imbalanced, accuracy alone may give an incomplete picture of model performance.

The model is therefore evaluated using accuracy, precision, recall, F1-score, ROC-AUC, and a confusion matrix.

In [18]:
y_pred = baseline_model.predict(X_test)
y_prob = baseline_model.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred), 4))
print("Recall:", round(recall_score(y_test, y_pred), 4))
print("F1 Score:", round(f1_score(y_test, y_pred), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))

Accuracy: 0.8055
Precision: 0.6572
Recall: 0.5588
F1 Score: 0.604
ROC-AUC: 0.842

**Baseline performance:** The logistic regression model achieved 80.55% accuracy and a ROC-AUC of 0.842, indicating useful discriminatory ability between churners and non-churners.

For the churn class, precision was 65.72% and recall was 55.88%. This means that while approximately two-thirds of customers classified as churners were correctly identified, the model detected only around 56% of all customers who actually churned.

The F1-score of 0.604 reflects the balance between precision and recall. Since the business objective is customer retention, recall is particularly relevant because false negatives represent customers who churn but are not identified for potential intervention. However, the appropriate balance between precision and recall ultimately depends on the cost and effectiveness of retention actions.

In [19]:
cm = confusion_matrix(y_test, y_pred)

cm

array([[926, 109],
       [165, 209]])

In [20]:
tn, fp, fn, tp = cm.ravel()

print("True Negatives:", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives:", tp)

True Negatives: 926
False Positives: 109
False Negatives: 165
True Positives: 209

### Confusion Matrix Interpretation

The baseline model correctly identified 926 non-churners and 209 churners.

It produced 109 false positives, representing customers who were predicted to churn but actually remained, and 165 false negatives, representing customers who churned despite being predicted to remain.

For a retention use case, the 165 false negatives are particularly important because these customers would not have been identified for potential retention intervention under the default classification threshold.

This highlights an important trade-off: increasing churn recall may identify more true churners, but it may also increase the number of false positives and therefore the cost of retention campaigns.

In [21]:
threshold_results = []

for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
    y_pred_threshold = (y_prob >= threshold).astype(int)

    threshold_results.append({
        "Threshold": threshold,
        "Precision": precision_score(y_test, y_pred_threshold),
        "Recall": recall_score(y_test, y_pred_threshold),
        "F1": f1_score(y_test, y_pred_threshold)
    })

threshold_results = pd.DataFrame(threshold_results).round(3)

threshold_results

   Threshold  Precision  Recall     F1
0        0.3      0.519   0.754  0.615
1        0.4      0.568   0.668  0.614
2        0.5      0.657   0.559  0.604
3        0.6      0.718   0.401  0.515
4        0.7      0.742   0.184  0.296

### Classification Threshold Analysis

Changing the classification threshold demonstrates the trade-off between precision and recall.

At the default threshold of 0.50, the model achieves 65.7% precision and 55.9% recall. Lowering the threshold to 0.30 increases recall to 75.4%, allowing the model to identify a larger proportion of customers who actually churn, while precision decreases to 51.9%.

Conversely, increasing the threshold improves precision but substantially reduces recall. For example, at a threshold of 0.70, precision increases to 74.2% while recall falls to only 18.4%.

The appropriate classification threshold therefore depends on the business costs associated with missed churners and unnecessary retention interventions. Threshold selection will be revisited when customer value and retention economics are incorporated into the project.

In [22]:
majority_accuracy = y_test.value_counts(normalize=True).max()

print("Majority-class baseline accuracy:", round(majority_accuracy, 4))
print("Logistic regression accuracy:", round(accuracy_score(y_test, y_pred), 4))

Majority-class baseline accuracy: 0.7346
Logistic regression accuracy: 0.8055

In [23]:
improvement = accuracy_score(y_test, y_pred) - majority_accuracy

print(
    "Accuracy improvement over majority baseline:",
    round(improvement, 4)
)

Accuracy improvement over majority baseline: 0.071

## 6. Model Comparison

The logistic regression model provides an interpretable baseline. A Random Forest classifier is now trained to determine whether a nonlinear, tree-based model can improve churn prediction performance.

The same train/test split is retained to ensure a fair comparison between models.

In [25]:
random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            RandomForestClassifier(
                n_estimators=300,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

In [26]:
random_forest_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=300, n_jobs=-1,
                                        random_state=42))])

In [27]:
rf_pred = random_forest_model.predict(X_test)
rf_prob = random_forest_model.predict_proba(X_test)[:, 1]

In [28]:
print("Accuracy:", round(accuracy_score(y_test, rf_pred), 4))
print("Precision:", round(precision_score(y_test, rf_pred), 4))
print("Recall:", round(recall_score(y_test, rf_pred), 4))
print("F1 Score:", round(f1_score(y_test, rf_pred), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, rf_prob), 4))

Accuracy: 0.7821
Precision: 0.6159
Recall: 0.4759
F1 Score: 0.537
ROC-AUC: 0.8196

### Random Forest Comparison

The untuned Random Forest did not outperform the logistic regression baseline.

Random Forest achieved a ROC-AUC of 0.820 compared with 0.842 for logistic regression. It also produced lower accuracy, precision, recall, and F1-score.

In particular, recall decreased from 55.9% with logistic regression to 47.6% with Random Forest, meaning that the Random Forest missed a larger proportion of customers who actually churned.

These results demonstrate that greater model complexity does not necessarily produce better predictive performance. Logistic regression remains the stronger model at this stage, although further models and tuning will be evaluated before selecting a final approach.

In [29]:
model_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, rf_pred)
    ],
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, rf_pred)
    ],
    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, rf_pred)
    ],
    "F1": [
        f1_score(y_test, y_pred),
        f1_score(y_test, rf_pred)
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, y_prob),
        roc_auc_score(y_test, rf_prob)
    ]
})

model_results.round(4)

                 Model  Accuracy  Precision  Recall     F1  ROC-AUC
0  Logistic Regression    0.8055     0.6572  0.5588  0.604   0.8420
1        Random Forest    0.7821     0.6159  0.4759  0.537   0.8196

### Gradient Boosting Model

A Gradient Boosting classifier is evaluated as an additional nonlinear model. Unlike Random Forest, which builds many trees independently, gradient boosting builds trees sequentially, with each stage attempting to improve upon errors made by the previous stages.

The same preprocessing pipeline and train/test split are retained to ensure comparability with the previous models.

In [31]:
gradient_boosting_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            GradientBoostingClassifier(
                random_state=42
            )
        )
    ]
)

In [32]:
gradient_boosting_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('classifier', GradientBoostingClassifier(random_state=42))])

In [33]:
gb_pred = gradient_boosting_model.predict(X_test)
gb_prob = gradient_boosting_model.predict_proba(X_test)[:, 1]

In [34]:
print("Accuracy:", round(accuracy_score(y_test, gb_pred), 4))
print("Precision:", round(precision_score(y_test, gb_pred), 4))
print("Recall:", round(recall_score(y_test, gb_pred), 4))
print("F1 Score:", round(f1_score(y_test, gb_pred), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, gb_prob), 4))

Accuracy: 0.8027
Precision: 0.6655
Recall: 0.516
F1 Score: 0.5813
ROC-AUC: 0.8433

### Gradient Boosting Comparison

Gradient Boosting achieved a ROC-AUC of 0.843, slightly higher than the logistic regression baseline at 0.842. It also achieved the highest precision of the three models at 66.6%.

However, at the default classification threshold, its recall of 51.6% and F1-score of 0.581 were lower than logistic regression's recall of 55.9% and F1-score of 0.604.

The difference in ROC-AUC between logistic regression and Gradient Boosting is very small, so these test-set results alone are not sufficient to conclude that one model is definitively superior. More robust model comparison using cross-validation will be performed before model selection.

In [35]:
model_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, gb_pred)
    ],
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, rf_pred),
        precision_score(y_test, gb_pred)
    ],
    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, rf_pred),
        recall_score(y_test, gb_pred)
    ],
    "F1": [
        f1_score(y_test, y_pred),
        f1_score(y_test, rf_pred),
        f1_score(y_test, gb_pred)
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, y_prob),
        roc_auc_score(y_test, rf_prob),
        roc_auc_score(y_test, gb_prob)
    ]
})

model_results.round(4)

                 Model  Accuracy  Precision  Recall      F1  ROC-AUC
0  Logistic Regression    0.8055     0.6572  0.5588  0.6040   0.8420
1        Random Forest    0.7821     0.6159  0.4759  0.5370   0.8196
2    Gradient Boosting    0.8027     0.6655  0.5160  0.5813   0.8433

## 7. Cross-Validation

Performance on a single train/test split can vary depending on which customers happen to be included in each set.

To obtain a more robust estimate of model performance, 5-fold stratified cross-validation is performed using only the training data. Stratification preserves the churn proportion within each fold.

The held-out test set is not used during cross-validation and remains reserved for final model evaluation.

In [37]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [38]:
scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

In [39]:
models = {
    "Logistic Regression": baseline_model,
    "Random Forest": random_forest_model,
    "Gradient Boosting": gradient_boosting_model
}

cv_results = []

for model_name, model in models.items():
    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    cv_results.append({
        "Model": model_name,
        "Accuracy": scores["test_accuracy"].mean(),
        "Precision": scores["test_precision"].mean(),
        "Recall": scores["test_recall"].mean(),
        "F1": scores["test_f1"].mean(),
        "ROC-AUC": scores["test_roc_auc"].mean()
    })

cv_results = pd.DataFrame(cv_results)

cv_results.round(4)

                 Model  Accuracy  Precision  Recall      F1  ROC-AUC
0  Logistic Regression    0.8019     0.6521  0.5438  0.5924   0.8461
1        Random Forest    0.7881     0.6325  0.4829  0.5473   0.8209
2    Gradient Boosting    0.8035     0.6627  0.5291  0.5882   0.8482

### Cross-Validation Results

The cross-validation results are broadly consistent with the initial test-set evaluation.

Gradient Boosting achieved the highest mean ROC-AUC at 0.848, closely followed by Logistic Regression at 0.846. The difference between these models is small.

Logistic Regression achieved slightly higher mean recall (0.544) and F1-score (0.592), while Gradient Boosting achieved slightly higher precision (0.663) and accuracy (0.804).

Random Forest produced lower ROC-AUC, recall, and F1-score than the other two models.

Overall, Logistic Regression and Gradient Boosting are the strongest candidates at this stage. Because their ROC-AUC performance is very similar, model selection should consider not only discrimination performance but also recall, threshold behaviour, interpretability, and ultimately the business cost of retention decisions.

In [42]:
cv_results = []

for model_name, model in models.items():
    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    cv_results.append({
        "Model": model_name,
        "Accuracy": scores["test_accuracy"].mean(),
        "Precision": scores["test_precision"].mean(),
        "Recall": scores["test_recall"].mean(),
        "F1": scores["test_f1"].mean(),
        "ROC-AUC": scores["test_roc_auc"].mean(),
        "ROC-AUC Std": scores["test_roc_auc"].std()
    })

cv_results = pd.DataFrame(cv_results)

cv_results.round(4)

,Model,Accuracy,Precision,Recall,F1,ROC-AUC,ROC-AUC Std
0,Logistic Regression,0.8019,0.6521,0.5438,0.5924,0.8461,0.0126
1,Random Forest,0.7881,0.6325,0.4829,0.5473,0.8209,0.0123
2,Gradient Boosting,0.8035,0.6627,0.5291,0.5882,0.8482,0.0125